version: "3.8"

services:
  db:
    image: postgres:17.4
    env_file: .env
    volumes:
      - ./.docker/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app/
      - ./info_board/employee/migrations:/app/info_board/employee/migrations
      - ./info_board/schedule/migrations:/app/info_board/schedule/migrations
    ports:
      - "8000:8000"

  redis:
    image: redis:7.4.2
    restart: unless-stopped
    volumes:
      - ./.docker/redis-data:/data

  celery:
    <<: *web
    command: "celery -A info_board worker -l info"
    depends_on:
      - redis
    ports: []
    container_name: info_board_celery
